In [164]:
import numpy as np  

In [165]:
myarr = np.array([[3, 6, 32, 7]], np.int64)
myarr

array([[ 3,  6, 32,  7]])

In [166]:
myarr[0,1]

6

In [167]:
myarr.shape

(1, 4)

In [168]:
myarr.dtype

dtype('int64')

In [169]:
myarr[0,1] = 45

In [170]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation: Conversion from other python Structure

In [171]:
listarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
listarray.dtype

dtype('int64')

In [173]:
listarray.shape

(3, 3)

In [174]:
listarray.size

9

In [175]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [176]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [177]:
one = np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [178]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [179]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [180]:
lspace2 = np.linspace(1,4,4)
lspace2


array([1., 2., 3., 4.])

In [181]:
emp = np.empty((4,6))
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.40264195e+175],
       [2.31584178e+077, 2.31584178e+077, 6.42285340e-323,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [182]:
emp2 = np.empty((8,9))
emp2

array([[ 2.23243159e-314,  2.34343781e-056,  0.00000000e+000,
         3.95252517e-323,  1.47763627e+248,  1.16096346e-028,
         7.69165785e+218,  1.35617292e+248,  6.14641328e-042],
       [ 3.40264195e+175,  3.95298584e+179,  1.45162217e+165,
         4.30514483e-096,  6.32299154e+233,  6.48224638e+170,
         5.22411352e+257,  5.74020278e+180,  8.37174974e-144],
       [ 1.41529402e+161,  6.00736899e-067,  4.73936857e+097,
         1.20143026e-071,  3.58965839e+126,  1.58268989e-319,
        -4.33114910e-311,  2.31584178e+077,  6.91691904e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  4.94065646e-324,
         4.94065646e-324,  0.00000000e+000,  0.00000000e+000],
       [ 2.15681104e-314,  0.00000000e+000,  0.00000000e+000,
   

In [183]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [184]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [185]:
ide.shape

(45, 45)

In [186]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [187]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [188]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [189]:
arr.shape

(99,)

In [190]:
ar = np.array([[4,2,5], [2,7,6], [3,8,4]])
ar

array([[4, 2, 5],
       [2, 7, 6],
       [3, 8, 4]])

In [191]:
ar.sum(axis=0)

array([ 9, 17, 15])

In [192]:
ar.sum(axis=1)

array([11, 15, 15])

In [193]:
ar.T

array([[4, 2, 3],
       [2, 7, 8],
       [5, 6, 4]])

In [194]:
ar.flat

In [195]:
for i in ar.flat:
    print(i)


4
2
5
2
7
6
3
8
4


In [196]:
ar.ndim

2

In [197]:
ar.size

9

In [198]:
ar.nbytes

72

In [199]:
one = np.array([2, 6, 45, 20, 1])
one

array([ 2,  6, 45, 20,  1])

In [200]:
one.argmax()

2

In [201]:
one.argmin()

4

In [202]:
one.argsort()

array([4, 0, 1, 3, 2])

In [203]:
ar

array([[4, 2, 5],
       [2, 7, 6],
       [3, 8, 4]])

In [204]:
ar.argmax()

7

In [205]:
ar.argmin()

1

In [206]:
ar.argmax(axis=0)

array([0, 2, 1])

In [207]:
ar.argmax(axis=1)

array([2, 1, 1])

In [208]:
ar.argsort(axis=0)

array([[1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [209]:
ar.argsort(axis=1)

array([[1, 0, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [210]:
ar.ravel()

array([4, 2, 5, 2, 7, 6, 3, 8, 4])

In [211]:
ar.reshape(9,1)

array([[4],
       [2],
       [5],
       [2],
       [7],
       [6],
       [3],
       [8],
       [4]])

In [212]:
ar

array([[4, 2, 5],
       [2, 7, 6],
       [3, 8, 4]])

In [213]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
ar +ar2

array([[ 5,  4,  8],
       [ 6, 12, 12],
       [10, 16, 13]])

In [215]:
ar - ar2

array([[ 3,  0,  2],
       [-2,  2,  0],
       [-4,  0, -5]])

In [216]:
ar * ar2

array([[ 4,  4, 15],
       [ 8, 35, 36],
       [21, 64, 36]])

In [217]:
np.sqrt(ar)

array([[2.        , 1.41421356, 2.23606798],
       [1.41421356, 2.64575131, 2.44948974],
       [1.73205081, 2.82842712, 2.        ]])

In [218]:
ar

array([[4, 2, 5],
       [2, 7, 6],
       [3, 8, 4]])

In [219]:
ar.sum()

41

In [220]:
ar.max()

8

In [221]:
ar.min()

2

In [222]:
ar.mean()

4.555555555555555

In [223]:
np.where(ar>5)

(array([1, 1, 2]), array([1, 2, 1]))

In [224]:
ar

array([[4, 2, 5],
       [2, 7, 6],
       [3, 8, 4]])

In [225]:
ar.tolist()

[[4, 2, 5], [2, 7, 6], [3, 8, 4]]

In [226]:
array1 = np.array([[3,2,5,7,0], [1,12,3,4,5]])
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [227]:
print(type(array1))

<class 'numpy.ndarray'>


In [228]:
array1.shape

(2, 5)

In [229]:
array1.dtype

dtype('int64')

In [230]:
array1 = np.array([[3,2.1,5,7,6], [1,12,3,4,5]], dtype="int32")
array1

array([[ 3,  2,  5,  7,  6],
       [ 1, 12,  3,  4,  5]], dtype=int32)

In [231]:
array1.dtype

dtype('int32')

In [232]:
np.zeros(4)

array([0., 0., 0., 0.])

In [233]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [234]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [235]:
np.ones(5).dtype

dtype('float64')

In [236]:
np.empty((4,6))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.40264195e+175],
       [2.31584178e+077, 2.31584178e+077, 6.42285340e-323,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [237]:
array1

array([[ 3,  2,  5,  7,  6],
       [ 1, 12,  3,  4,  5]], dtype=int32)

In [238]:
array1+array1

array([[ 6,  4, 10, 14, 12],
       [ 2, 24,  6,  8, 10]], dtype=int32)

In [239]:
array1 - array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [240]:
array1 * array1

array([[  9,   4,  25,  49,  36],
       [  1, 144,   9,  16,  25]], dtype=int32)

In [241]:
array1 / array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [242]:
array1 ** array1 

array([[        27,          4,       3125,     823543,      46656],
       [         1, -251658240,         27,        256,       3125]],
      dtype=int32)

In [243]:
10/array1

array([[ 3.33333333,  5.        ,  2.        ,  1.42857143,  1.66666667],
       [10.        ,  0.83333333,  3.33333333,  2.5       ,  2.        ]])

## Slicing 

In [244]:
array2 = np.array([5,4,64,3,3,3])
array2

array([ 5,  4, 64,  3,  3,  3])

In [246]:
array2[0:2]

array([5, 4])

In [249]:
arr5 = np.array([[2,3,5],[6,1,9],[1,2,3]])
arr5

array([[2, 3, 5],
       [6, 1, 9],
       [1, 2, 3]])

In [250]:
arr5[0,0]

2

In [253]:
arr5[0,2]

5

In [257]:
arr5[2,1]

2

In [259]:
arr5[2,2]

3

In [261]:
arr5[1,2]

9